apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: roboshop
  labels:
    project: roboshop
    component: nginx
spec:
  replicas: 1
  selector:
    matchLabels: 
      project: roboshop
      component: nginx
  template:
    metadata:
      labels:
        project: roboshop
        component: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest