apiVersion: apps/v1
kind: Deployment
metadata:
  name: taint-tolerations
  labels:
    project: roboshop
    environment: development
    purpose: tolerations-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: development
      purpose: tolerations-demo
  template:
    metadata:
      labels:
        project: roboshop
        environment: development
        purpose: tolerations-demo
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-22-110.ec2.internal                                                                                                            │
      containers:
      - name: nginx
        image: nginx:latest
